# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  - master
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"
          - script: |
              cd AngularWithAzure/
              npm install -g @angular/cli
              npm install
              ng build --prod                   
            displayName: "npm install and build"
            workingDirectory: '$(Build.SourcesDirectory)'
          - task: CmdLine@2
            displayName: "Run unit tests"
            inputs:
              script: |
                cd AngularWithAzure/
                ng test --browsers=ChromeHeadless --code-coverage --watch=false
          - task: CopyFiles@2
            inputs:
              SourceFolder: "dist/*"
              Contents: "**"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
  - stage: Deployment
    displayName: Deploy to S3
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # do not run the deploy for PR builds
    jobs:
      - deployment:
        pool:
          vmImage: "ubuntu-latest"
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
                  inputs:
                    awsCredentials: 'aws'
                    regionName: "us-east-1"
                    bucketName: "dev-s3-azure"
                    sourceFolder: "$(Pipeline.Workspace)/referencia/"
                    globExpressions: "**"
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: 'aws'
                    regionName: 'us-east-1'
                    awsCommand: 'cloudfront'
                    awsSubCommand: 'create-invalidation'
                    awsArguments: '--distribution-id E20Q0NIB5TQ39U --paths "/*"'
                  displayName: "Invalidate CloudFront Cache"